name: Coverage
on:
  workflow_dispatch
env:
    GITHUB_TOKEN: ${{ github.token }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: Generate Coverage Report
        run: |
          mvn -B package --file pom.xml
          
      # generates coverage-report.md and publishes as checkrun
      - name: Report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v4.9
        with:
          coverage_results_path: jacoco.xml
          coverage_report_name: Coverage
          coverage_report_title: JaCoCo
          github_token: GITHUB_TOKEN
          skip_check_run: false
          minimum_coverage: 80
          fail_below_threshold: false
          publish_only_summary: false

      # Publish Coverage Job Summary  # Optional
      - name: Add Coverage Job Summary
        run: echo "${{ steps.jacoco_reporter.outputs.coverageSummary }}" >> $GITHUB_STEP_SUMMARY

      - name: Publish report
        uses: actions/upload-artefact@v3
        with:
          name: report
          path: SampleArtefact
